MACRO(REQUIRE_HEADER var header)
  FIND_PATH(${var} ${header})
  IF(${${var}} STREQUAL "${var}-NOTFOUND")
    MESSAGE(SEND_ERROR "Required header ${header} not found")
  ELSE(${${var}} STREQUAL "${var}-NOTFOUND")
    INCLUDE_DIRECTORIES(${${var}})
  ENDIF(${${var}} STREQUAL "${var}-NOTFOUND")
ENDMACRO(REQUIRE_HEADER var header)

MACRO(FIND_AND_LINK_LIBRARY library target)
  FIND_LIBRARY(${library}_LIBRARY ${library})
  IF(${${library}_LIBRARY} STREQUAL ${library}_LIBRARY-NOTFOUND)
    MESSAGE(SEND_ERROR "Required library ${library} not found")
  ELSE(${${library}_LIBRARY} STREQUAL ${library}_LIBRARY-NOTFOUND)
    TARGET_LINK_LIBRARIES(${target} ${${library}_LIBRARY})
  ENDIF(${${library}_LIBRARY} STREQUAL ${library}_LIBRARY-NOTFOUND)
ENDMACRO(FIND_AND_LINK_LIBRARY library target)
